import './style.css'
export { default as Apps } from './components/Apps.vue'
export { default as Comment } from './components/Comment.vue'
// export { default as Download } from './components/Download.vue'
export { default as Footer } from './components/Footer.vue'
export { default as Section } from './components/Section.vue'
export { default as Video } from './components/Video.vue'
export { default as Compare } from './components/feature/Compare.vue'
export { default as FeatureSingle } from './components/feature/FeatureSingle.vue'
export { default as Grid } from './components/feature/Grid.vue'
export { default as Infinite } from './components/feature/Infinite.vue'
export { default as TwoCol } from './components/feature/TwoCol.vue'
